spin_manifest_version = 2

[application]
name = "dioxus-test"
version = "0.1.0"
description = "Minimal Dioxus Test Application"

[[trigger.http]]
route = "/..."
component = "dioxus-test"

[component.dioxus-test]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.0.1/spin_static_fs.wasm", digest = "sha256:650376c33a0756b1a52cad7ca670f1126391b79050df0321407da9c741d32375" }
files = [{ source = "target/dx/dioxus-test/release/web/public", destination = "/" }]
environment = { FALLBACK_PATH = "index.html" }
