[package]
name = "frontend-dioxus"
version = "0.1.0"
authors = ["wizard supreme <smn7818@gmail.com>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.6.3", features = ["router", "fullstack", "web"] }
wasm-logger = "0.2.0"
log = "0.4.27"
wasm-bindgen = "0.2.100"
web-sys = { version = "0.3.70", features = ["Window", "Storage"] }
chrono = "0.4.38"
serde_json = "1.0.128"
tokio = { version = "1.44.2", features = ["rt", "time"], default-features = false }

[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
