[package]
name = "djibon-web"
version = "0.1.0"
authors = ["wizard supreme <smn7818@gmail.com>"]
edition = "2024"

[dependencies]
dioxus = { version = "0.6.3", features = ["web", "router", "signals"] }
log = "0.4.27"
wasm-logger = "0.2.0"

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
