[application]
name = "DJibon"
default_platform = "android"
out_dir = "dist"

[web.app]

# HTML title tag content
title = "frontend-dioxus"

# Content Security Policy
content_security_policy = "default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[web.dev]
# The port to serve on
port = 3300

[android]
app_name = "DJibon"
package_name = "com.djibon.app"
version_code = 1
version_name = "1.0.0"
minimum_sdk_version = 21
target_sdk_version = 33
icon = "assets/favicon.ico"
activity_name = "MainActivity"
