[application]
name = "djibon-web"
title = "Djibon"

[web.app]
index_on_404 = true
template = "public/error.html"

[web.assets]
assets_dir = "public"

[bundle]
identifier = "com.djibon.app"

[android]
app_name = "Djibon"
assets_dir = "public"
icon = "public/djibon-icon.png"
version_code = 1
version_name = "0.0.2"
minimum_sdk_version = 24 
target_sdk_version = 33
full_screen = false
screen_orientation = "unspecified"
