[application]
name = "djibon-web"
title = "Djibon PACT"
content_security_policy = "default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;"

[web.resources]
style = ["/assets/bootstrap.min.css"]
script = ["/assets/bootstrap.bundle.min.js"]

[web.watcher]
port = 4200

# Add this to specify the assets directory
[web.assets]
assets_dir = "../../assets"
