[application]
name = "Jeebon"
title = "Jeebon"
asset_dir = "public"  # This is needed on the dioxus 6.3+

[web.app]
index_on_404 = true
template = "public/error.html"

[web.assets]
assets_dir = "public" # this will not work past dioxus 6.3

[web.watcher]
compress = true

[bundle]
identifier = "ai.jeebon.app"

[android]
app_name = "jeebon"
assets_dir = "public" # this is still needed on dioxus 6.3+. Rely on [application].asset_dir for web only
icon = "public/jeebon-icon.png"
version_code = 1
version_name = "0.0.23"
minimum_sdk_version = 30 
target_sdk_version = 33
full_screen = false
screen_orientation = "unspecified"
