[application]
name = "jiboni"
title = "Jiboni"
asset_dir = "public"  # This is needed on the dioxus 6.3+

[web.app]
index_on_404 = true
template = "public/error.html"

[web.assets]
assets_dir = "public" # this will not work past dioxus 6.3

[web.watcher]
compress = true

[bundle]
identifier = "com.jiboni.app"

[android]
app_name = "Jiboni"
assets_dir = "public" # this will not work past dioxus 6.3
icon = "public/jiboni-icon.png"
version_code = 1
version_name = "0.0.2"
minimum_sdk_version = 30 
target_sdk_version = 33
full_screen = false
screen_orientation = "unspecified"
