spin_manifest_version = 2

[application]
name = "djibon-web"
version = "0.1.0"
description = "Djibon PACT - Personal Assistance and Communication Tool"

[[trigger.http]]
route = "/..."
component = "djibon-web"

[component.djibon-web]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.0.1/spin_static_fs.wasm", digest = "sha256:650376c33a0756b1a52cad7ca670f1126391b79050df0321407da9c741d32375" }
files = [{ source = "target/dx/frontend-dioxus/release/web/public", destination = "/" }]
environment = { FALLBACK_PATH = "index.html" }