name = "jiboni-dev"
compatibility_date = "2025-04-26"
pages_build_output_dir = "./target/dx/jiboni/release/web/public"

[site]
  [site.mimeTypes]
  "text/html" = ["html"]
  "text/javascript" = ["js"]
  "text/css" = ["css"]