name = "djibon-web"
compatibility_date = "2025-04-26"

# Build configuration
[build]
command = "dx build --release"

# Pages specific configuration - using the correct field name
pages_build_output_dir = "target/dx/frontend-dioxus/release/web/public"
