name: Deploy Download Page

on:
  workflow_run:
    workflows: ["Build Android App and Deploy", "Build iOS App and Deploy"]
    types:
      - completed

jobs:
  deploy-download:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Create download directory
        run: mkdir -p download-page
      
      - name: Download Android artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-android.yml
          workflow_conclusion: success
          name: android-build
          path: download-page
          if_no_artifact_found: ignore
      
      - name: Download iOS artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-ios.yml
          workflow_conclusion: success
          name: ios-build
          path: download-page
          if_no_artifact_found: ignore
      
      - name: List download directory contents
        run: ls -la download-page
      
      - name: Check if any artifacts were downloaded
        id: check-artifacts
        run: |
          if [ -z "$(ls -A download-page)" ]; then
            echo "No artifacts found, skipping deployment"
            echo "has_artifacts=false" >> $GITHUB_OUTPUT
          else
            echo "Artifacts found, proceeding with deployment"
            echo "has_artifacts=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Deploy to Cloudflare Pages
        if: steps.check-artifacts.outputs.has_artifacts == 'true'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          workingDirectory: 'download-page'
          command: pages deploy . --project-name=djibon-download
