name: Deploy Download Page

on:
  push:
    branches:
      - main
    paths:
      - 'download-page/**'
  workflow_dispatch:  # Allow manual triggering

jobs:
  deploy-download-page:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List download page files
        run: |
          echo "Files to be deployed:"
          ls -la download-page/

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages deploy ./download-page --project-name=djibon-download
