name: Update Version

on:
  workflow_call:
    inputs:
      version:
        description: 'Version number (x.x.x)'
        required: true
        type: string
    outputs:
      version:
        description: "The version that was set"
        value: ${{ jobs.update-version.outputs.version }}

jobs:
  update-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set version
        id: get-version
        run: |
          VERSION="${{ inputs.version }}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Using version: $VERSION"
      
      - name: Update version in Dioxus.toml and Cargo.toml
        run: |
          VERSION="${{ steps.get-version.outputs.version }}"
          
          # Update only the package version in Cargo.toml
          sed -i "/^\[package\]/,/^\[/ s/^version = \"[0-9]\+\.[0-9]\+\.[0-9]\+\"/version = \"$VERSION\"/" Cargo.toml
          
          # Update version_name in Dioxus.toml
          sed -i "s/version_name = \"[0-9]\+\.[0-9]\+\.[0-9]\+\"/version_name = \"$VERSION\"/g" Dioxus.toml
          
          echo "Updated version to $VERSION in Cargo.toml and Dioxus.toml"
      
      - name: Upload updated files
        uses: actions/upload-artifact@v3
        with:
          name: version-files
          path: |
            Cargo.toml
            Dioxus.toml
          retention-days: 1
